name: Deploy to Cloud Run on merge to main

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Insert your test commands here (e.g., pytest, linters, etc.)

  continuous_deployment:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: continuous_integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: promptbud

      - name: Set gcloud project configuration
        run: |
          gcloud config set project promptbud

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          IMAGE="${{ secrets.ARTIFACT_REGISTRY_URL }}"
          docker build -t $IMAGE .
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ secrets.ARTIFACT_REGISTRY_URL }}"
          gcloud run deploy prompt-assistant \
            --image=$IMAGE \
            --platform=managed \
            --region=us-east1 \
            --project=promptbud \
            --allow-unauthenticated \
            --memory=512Mi \
            --port=8080 \
            --set-env-vars=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}

