name: Deploy to Cloud Run on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: promptbud

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          IMAGE="us-east1-docker.pkg.dev/promptbud/prompt-bud/prompt-assistant"
          docker build -t $IMAGE .
          gcloud auth configure-docker us-east1-docker.pkg.dev
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="us-east1-docker.pkg.dev/promptbud/prompt-bud/prompt-assistant"
          gcloud run deploy prompt-assistant \
            --image=$IMAGE \
            --platform=managed \
            --region=us-east1 \
            --allow-unauthenticated \
            --memory=512Mi \
            --port=8080
