name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: promptbud
          install_components: 'beta'

      - name: Build and push Docker image
        run: |
          IMAGE="location-docker.pkg.dev/promptbud/promptbuddy/prompt-assistant"
          gcloud auth configure-docker location-docker.pkg.dev
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="location-docker.pkg.dev/promptbud/promptbuddy/prompt-assistant"
          gcloud run deploy prompt-assistant \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
